//HintName: GeneratedFunctionMetadataProvider.g.cs
// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Core.FunctionMetadata;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace TestProject
{
    /// <summary>
    /// Custom <see cref="IFunctionMetadataProvider"/> implementation that returns function metadata definitions for the current worker."/>
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneratedFunctionMetadataProvider : IFunctionMetadataProvider
    {
        /// <inheritdoc/>
        public Task<ImmutableArray<IFunctionMetadata>> GetFunctionMetadataAsync(string directory)
        {
            var metadataList = new List<IFunctionMetadata>();
            var Function0RawBindings = new List<string>();
            Function0RawBindings.Add(@"{""name"":""r"",""type"":""httpTrigger"",""direction"":""In""}");
            Function0RawBindings.Add(@"{""name"":""$return"",""type"":""http"",""direction"":""Out""}");

            var Function0 = new DefaultFunctionMetadata
            {
                Language = "dotnet-isolated",
                Name = "FunctionExactName",
                EntryPoint = "Foo.HttpTriggersWithPlainArguments.FunctionExactNameMethod",
                RawBindings = Function0RawBindings,
                ScriptFile = "TestProject.dll"
            };
            metadataList.Add(Function0);
            var Function1RawBindings = new List<string>();
            Function1RawBindings.Add(@"{""name"":""r"",""type"":""httpTrigger"",""direction"":""In""}");
            Function1RawBindings.Add(@"{""name"":""$return"",""type"":""http"",""direction"":""Out""}");

            var Function1 = new DefaultFunctionMetadata
            {
                Language = "dotnet-isolated",
                Name = "WithDefaultCtorShort",
                EntryPoint = "Foo.HttpTriggersWithPlainArguments.WithDefaultCtorShort",
                RawBindings = Function1RawBindings,
                ScriptFile = "TestProject.dll"
            };
            metadataList.Add(Function1);
            var Function2RawBindings = new List<string>();
            Function2RawBindings.Add(@"{""name"":""r"",""type"":""httpTrigger"",""direction"":""In""}");
            Function2RawBindings.Add(@"{""name"":""$return"",""type"":""http"",""direction"":""Out""}");

            var Function2 = new DefaultFunctionMetadata
            {
                Language = "dotnet-isolated",
                Name = "WithDefaultCtor",
                EntryPoint = "Foo.HttpTriggersWithPlainArguments.WithDefaultCtor",
                RawBindings = Function2RawBindings,
                ScriptFile = "TestProject.dll"
            };
            metadataList.Add(Function2);
            var Function3RawBindings = new List<string>();
            Function3RawBindings.Add(@"{""name"":""r"",""type"":""httpTrigger"",""direction"":""In"",""methods"":[""get"",""post""]}");
            Function3RawBindings.Add(@"{""name"":""$return"",""type"":""http"",""direction"":""Out""}");

            var Function3 = new DefaultFunctionMetadata
            {
                Language = "dotnet-isolated",
                Name = "WithMethodsOnly",
                EntryPoint = "Foo.HttpTriggersWithPlainArguments.WithMethodsOnly",
                RawBindings = Function3RawBindings,
                ScriptFile = "TestProject.dll"
            };
            metadataList.Add(Function3);
            var Function4RawBindings = new List<string>();
            Function4RawBindings.Add(@"{""name"":""r"",""type"":""httpTrigger"",""direction"":""In"",""authLevel"":""Function""}");
            Function4RawBindings.Add(@"{""name"":""$return"",""type"":""http"",""direction"":""Out""}");

            var Function4 = new DefaultFunctionMetadata
            {
                Language = "dotnet-isolated",
                Name = "WithAuthMethodOnly",
                EntryPoint = "Foo.HttpTriggersWithPlainArguments.WithAuthMethodOnly",
                RawBindings = Function4RawBindings,
                ScriptFile = "TestProject.dll"
            };
            metadataList.Add(Function4);
            var Function5RawBindings = new List<string>();
            Function5RawBindings.Add(@"{""name"":""r"",""type"":""httpTrigger"",""direction"":""In"",""authLevel"":""Function"",""methods"":[""get""]}");
            Function5RawBindings.Add(@"{""name"":""$return"",""type"":""http"",""direction"":""Out""}");

            var Function5 = new DefaultFunctionMetadata
            {
                Language = "dotnet-isolated",
                Name = "WithAuthLevelAndMethods",
                EntryPoint = "Foo.HttpTriggersWithPlainArguments.WithAuthLevelAndMethods",
                RawBindings = Function5RawBindings,
                ScriptFile = "TestProject.dll"
            };
            metadataList.Add(Function5);
            var Function6RawBindings = new List<string>();
            Function6RawBindings.Add(@"{""name"":""r"",""type"":""httpTrigger"",""direction"":""In"",""authLevel"":""Function"",""methods"":[""get""],""route"":""route""}");
            Function6RawBindings.Add(@"{""name"":""$return"",""type"":""http"",""direction"":""Out""}");

            var Function6 = new DefaultFunctionMetadata
            {
                Language = "dotnet-isolated",
                Name = "WithAuthLevelAndMethodsAndRoutes",
                EntryPoint = "Foo.HttpTriggersWithPlainArguments.WithAuthLevelAndMethodsAndRoutes",
                RawBindings = Function6RawBindings,
                ScriptFile = "TestProject.dll"
            };
            metadataList.Add(Function6);
            var Function7RawBindings = new List<string>();
            Function7RawBindings.Add(@"{""name"":""r"",""type"":""httpTrigger"",""direction"":""In""}");
            Function7RawBindings.Add(@"{""name"":""$return"",""type"":""http"",""direction"":""Out""}");

            var Function7 = new DefaultFunctionMetadata
            {
                Language = "dotnet-isolated",
                Name = "FunctionExactName",
                EntryPoint = "Foo.HttpTriggersWithConsts.FunctionExactNameMethod",
                RawBindings = Function7RawBindings,
                ScriptFile = "TestProject.dll"
            };
            metadataList.Add(Function7);
            var Function8RawBindings = new List<string>();
            Function8RawBindings.Add(@"{""name"":""r"",""type"":""httpTrigger"",""direction"":""In""}");
            Function8RawBindings.Add(@"{""name"":""$return"",""type"":""http"",""direction"":""Out""}");

            var Function8 = new DefaultFunctionMetadata
            {
                Language = "dotnet-isolated",
                Name = "WithDefaultCtorShort",
                EntryPoint = "Foo.HttpTriggersWithConsts.WithDefaultCtorShort",
                RawBindings = Function8RawBindings,
                ScriptFile = "TestProject.dll"
            };
            metadataList.Add(Function8);
            var Function9RawBindings = new List<string>();
            Function9RawBindings.Add(@"{""name"":""r"",""type"":""httpTrigger"",""direction"":""In""}");
            Function9RawBindings.Add(@"{""name"":""$return"",""type"":""http"",""direction"":""Out""}");

            var Function9 = new DefaultFunctionMetadata
            {
                Language = "dotnet-isolated",
                Name = "WithDefaultCtor",
                EntryPoint = "Foo.HttpTriggersWithConsts.WithDefaultCtor",
                RawBindings = Function9RawBindings,
                ScriptFile = "TestProject.dll"
            };
            metadataList.Add(Function9);
            var Function10RawBindings = new List<string>();
            Function10RawBindings.Add(@"{""name"":""r"",""type"":""httpTrigger"",""direction"":""In"",""methods"":[""post""]}");
            Function10RawBindings.Add(@"{""name"":""$return"",""type"":""http"",""direction"":""Out""}");

            var Function10 = new DefaultFunctionMetadata
            {
                Language = "dotnet-isolated",
                Name = "WithMethodsOnly",
                EntryPoint = "Foo.HttpTriggersWithConsts.WithMethodsOnly",
                RawBindings = Function10RawBindings,
                ScriptFile = "TestProject.dll"
            };
            metadataList.Add(Function10);
            var Function11RawBindings = new List<string>();
            Function11RawBindings.Add(@"{""name"":""r"",""type"":""httpTrigger"",""direction"":""In"",""authLevel"":""Function""}");
            Function11RawBindings.Add(@"{""name"":""$return"",""type"":""http"",""direction"":""Out""}");

            var Function11 = new DefaultFunctionMetadata
            {
                Language = "dotnet-isolated",
                Name = "WithAuthMethodOnly",
                EntryPoint = "Foo.HttpTriggersWithConsts.WithAuthMethodOnly",
                RawBindings = Function11RawBindings,
                ScriptFile = "TestProject.dll"
            };
            metadataList.Add(Function11);
            var Function12RawBindings = new List<string>();
            Function12RawBindings.Add(@"{""name"":""r"",""type"":""httpTrigger"",""direction"":""In"",""authLevel"":""Function"",""methods"":[""post""]}");
            Function12RawBindings.Add(@"{""name"":""$return"",""type"":""http"",""direction"":""Out""}");

            var Function12 = new DefaultFunctionMetadata
            {
                Language = "dotnet-isolated",
                Name = "WithAuthLevelAndMethods",
                EntryPoint = "Foo.HttpTriggersWithConsts.WithAuthLevelAndMethods",
                RawBindings = Function12RawBindings,
                ScriptFile = "TestProject.dll"
            };
            metadataList.Add(Function12);
            var Function13RawBindings = new List<string>();
            Function13RawBindings.Add(@"{""name"":""r"",""type"":""httpTrigger"",""direction"":""In"",""authLevel"":""Function"",""methods"":[""post""],""route"":""function-prefix""}");
            Function13RawBindings.Add(@"{""name"":""$return"",""type"":""http"",""direction"":""Out""}");

            var Function13 = new DefaultFunctionMetadata
            {
                Language = "dotnet-isolated",
                Name = "WithAuthLevelAndMethodsAndRoutes",
                EntryPoint = "Foo.HttpTriggersWithConsts.WithAuthLevelAndMethodsAndRoutes",
                RawBindings = Function13RawBindings,
                ScriptFile = "TestProject.dll"
            };
            metadataList.Add(Function13);
            var Function14RawBindings = new List<string>();
            Function14RawBindings.Add(@"{""name"":""r"",""type"":""httpTrigger"",""direction"":""In"",""authLevel"":""Function"",""methods"":[""post""],""route"":""function-prefix/other""}");
            Function14RawBindings.Add(@"{""name"":""$return"",""type"":""http"",""direction"":""Out""}");

            var Function14 = new DefaultFunctionMetadata
            {
                Language = "dotnet-isolated",
                Name = "WithAuthLevelAndMethodsAndRoutesInterpolated",
                EntryPoint = "Foo.HttpTriggersWithConsts.WithAuthLevelAndMethodsAndRoutesInterpolated",
                RawBindings = Function14RawBindings,
                ScriptFile = "TestProject.dll"
            };
            metadataList.Add(Function14);

            return Task.FromResult(metadataList.ToImmutableArray());
        }
    }

    /// <summary>
    /// Extension methods to enable registration of the custom <see cref="IFunctionMetadataProvider"/> implementation generated for the current worker.
    /// </summary>
    public static class WorkerHostBuilderFunctionMetadataProviderExtension
    {
        ///<summary>
        /// Adds the GeneratedFunctionMetadataProvider to the service collection.
        /// During initialization, the worker will return generated function metadata instead of relying on the Azure Functions host for function indexing.
        ///</summary>
        public static IHostBuilder ConfigureGeneratedFunctionMetadataProvider(this IHostBuilder builder)
        {
            builder.ConfigureServices(s => 
            {
                s.AddSingleton<IFunctionMetadataProvider, GeneratedFunctionMetadataProvider>();
            });
            return builder;
        }
    }
}