//HintName: GeneratedFunctionMetadataProvider.g.cs
// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Core.FunctionMetadata;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace TestProject
{
    /// <summary>
    /// Custom <see cref="IFunctionMetadataProvider"/> implementation that returns function metadata definitions for the current worker."/>
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneratedFunctionMetadataProvider : IFunctionMetadataProvider
    {
        /// <inheritdoc/>
        public Task<ImmutableArray<IFunctionMetadata>> GetFunctionMetadataAsync(string directory)
        {
            var metadataList = new List<IFunctionMetadata>();
            var Function0RawBindings = new List<string>();
            Function0RawBindings.Add(@"{""name"":""req"",""type"":""httpTrigger"",""direction"":""In"",""authLevel"":""Anonymous"",""methods"":[""get"",""post""]}");
            Function0RawBindings.Add(@"{""name"":""Name"",""type"":""queue"",""direction"":""Out"",""queueName"":""functionstesting2"",""connection"":""AzureWebJobsStorage""}");
            Function0RawBindings.Add(@"{""name"":""HttpResponse"",""type"":""http"",""direction"":""Out""}");

            var Function0 = new DefaultFunctionMetadata
            {
                Language = "dotnet-isolated",
                Name = "WithNestedOutput",
                EntryPoint = "FunctionApp.HttpTriggerSimple.WithNestedOutput",
                RawBindings = Function0RawBindings,
                ScriptFile = "TestProject.dll"
            };
            metadataList.Add(Function0);
            var Function1RawBindings = new List<string>();
            Function1RawBindings.Add(@"{""name"":""req"",""type"":""httpTrigger"",""direction"":""In"",""authLevel"":""Anonymous"",""methods"":[""get"",""post""]}");
            Function1RawBindings.Add(@"{""name"":""Name"",""type"":""queue"",""direction"":""Out"",""queueName"":""functionstesting2"",""connection"":""AzureWebJobsStorage""}");

            var Function1 = new DefaultFunctionMetadata
            {
                Language = "dotnet-isolated",
                Name = "WithNestedOutputTypesWithoutTypeDefinedOutput",
                EntryPoint = "FunctionApp.HttpTriggerSimple.WithNestedOutputTypesWithoutTypeDefinedOutput",
                RawBindings = Function1RawBindings,
                ScriptFile = "TestProject.dll"
            };
            metadataList.Add(Function1);
            var Function2RawBindings = new List<string>();
            Function2RawBindings.Add(@"{""name"":""req"",""type"":""httpTrigger"",""direction"":""In"",""authLevel"":""Anonymous"",""methods"":[""get"",""post""]}");
            Function2RawBindings.Add(@"{""name"":""Name"",""type"":""queue"",""direction"":""Out"",""queueName"":""functionstesting2"",""connection"":""AzureWebJobsStorage""}");
            Function2RawBindings.Add(@"{""name"":""HttpResponse"",""type"":""http"",""direction"":""Out""}");

            var Function2 = new DefaultFunctionMetadata
            {
                Language = "dotnet-isolated",
                Name = "ByAttribute",
                EntryPoint = "FunctionApp.HttpTriggerSimple.ByAttribute",
                RawBindings = Function2RawBindings,
                ScriptFile = "TestProject.dll"
            };
            metadataList.Add(Function2);
            var Function3RawBindings = new List<string>();
            Function3RawBindings.Add(@"{""name"":""req"",""type"":""httpTrigger"",""direction"":""In"",""authLevel"":""Anonymous"",""methods"":[""get"",""post""]}");
            Function3RawBindings.Add(@"{""name"":""Name"",""type"":""queue"",""direction"":""Out"",""queueName"":""functionstesting2"",""connection"":""AzureWebJobsStorage""}");
            Function3RawBindings.Add(@"{""name"":""Response"",""type"":""http"",""direction"":""Out""}");

            var Function3 = new DefaultFunctionMetadata
            {
                Language = "dotnet-isolated",
                Name = "GenericString",
                EntryPoint = "FunctionApp.HttpTriggerSimple.GenericString",
                RawBindings = Function3RawBindings,
                ScriptFile = "TestProject.dll"
            };
            metadataList.Add(Function3);
            var Function4RawBindings = new List<string>();
            Function4RawBindings.Add(@"{""name"":""req"",""type"":""httpTrigger"",""direction"":""In"",""authLevel"":""Anonymous"",""methods"":[""get"",""post""]}");
            Function4RawBindings.Add(@"{""name"":""Name"",""type"":""queue"",""direction"":""Out"",""queueName"":""functionstesting2"",""connection"":""AzureWebJobsStorage""}");
            Function4RawBindings.Add(@"{""name"":""Response"",""type"":""http"",""direction"":""Out""}");

            var Function4 = new DefaultFunctionMetadata
            {
                Language = "dotnet-isolated",
                Name = "GenericIActionResult",
                EntryPoint = "FunctionApp.HttpTriggerSimple.GenericIActionResult",
                RawBindings = Function4RawBindings,
                ScriptFile = "TestProject.dll"
            };
            metadataList.Add(Function4);
            var Function5RawBindings = new List<string>();
            Function5RawBindings.Add(@"{""name"":""req"",""type"":""httpTrigger"",""direction"":""In"",""authLevel"":""Anonymous"",""methods"":[""get"",""post""]}");
            Function5RawBindings.Add(@"{""name"":""Name"",""type"":""queue"",""direction"":""Out"",""queueName"":""functionstesting2"",""connection"":""AzureWebJobsStorage""}");
            Function5RawBindings.Add(@"{""name"":""Response"",""type"":""http"",""direction"":""Out""}");

            var Function5 = new DefaultFunctionMetadata
            {
                Language = "dotnet-isolated",
                Name = "GenericHttpResponseData",
                EntryPoint = "FunctionApp.HttpTriggerSimple.GenericHttpResponseData",
                RawBindings = Function5RawBindings,
                ScriptFile = "TestProject.dll"
            };
            metadataList.Add(Function5);

            return Task.FromResult(metadataList.ToImmutableArray());
        }
    }

    /// <summary>
    /// Extension methods to enable registration of the custom <see cref="IFunctionMetadataProvider"/> implementation generated for the current worker.
    /// </summary>
    public static class WorkerHostBuilderFunctionMetadataProviderExtension
    {
        ///<summary>
        /// Adds the GeneratedFunctionMetadataProvider to the service collection.
        /// During initialization, the worker will return generated function metadata instead of relying on the Azure Functions host for function indexing.
        ///</summary>
        public static IHostBuilder ConfigureGeneratedFunctionMetadataProvider(this IHostBuilder builder)
        {
            builder.ConfigureServices(s => 
            {
                s.AddSingleton<IFunctionMetadataProvider, GeneratedFunctionMetadataProvider>();
            });
            return builder;
        }
    }
}